import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { getAllPosts } from "../data/posts";
import styles from "../styles/Home.module.css";

const Home: NextPage = (props) => {
  return (
    <div
      //@ts-ignore
      style={{ backgroundColor: props.color }}
      className={styles.container}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <h1>Inspire</h1>
      </main>

      <Footer />
    </div>
  );
};

export const getServerSideProps = async () => {
  const posts = getAllPosts();

  const res = await axios.get(
    "https://random-data-api.com/api/color/random_color"
  );

  return { props: { color: res.data.hex_value } };
};

export default Home;
